modLoader = "kotlinforforge"
loaderVersion = "[5.3,)"
issueTrackerURL = "https://github.com/benjaminiserman/WingsContracts/issues"
license = "MIT"

[[mods]]
modId = "wingscontracts"
version = "${version}"
displayName = "Wing's Contracts"
authors = "benjaminiserman"
description = '''
Reward automation with bulk-order contracts.
'''
logoFile = "icon.png"

[[mixins]]
config = "wingscontracts.mixins.json"

[[dependencies.wingscontracts]]
modId="neoforge"
type="required"
versionRange="[21.0.0,)"

[[dependencies.wingscontracts]]
modId = "minecraft"
type="required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.wingscontracts]]
modId = "architectury"
type="required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wingscontracts]]
modId = "kotlinforforge"
type="required"
versionRange = "[${kotlin_for_forge_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wingscontracts]]
modId = "create"
type="optional"
versionRange = "${create_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wingscontracts]]
modId = "cc_tweaked"
type="optional"
versionRange = "[${cc_tweaked_version}]"
ordering = "AFTER"
side = "BOTH"